pages/index.tsx

TEST: Testing Pull Request

---

app/(NoLogoPages)/StatusMgr/page.tsx
app/(NoLogoPages)/layout.tsx
components/Status/GroupStatus.tsx
components/Status/MemberStatus.tsx
components/static/ReturnButton.tsx
next.config.mjs

this branch contains the page that the manager sees after creating the group but didn't take the  quiz yet . there is another page after he finishes the quiz which quite similar but will be on another branch.

added the whole content for the StatusMgr page

---

app/testRestaurant/page.tsx
pages/api/findBestRestaurant.js
pages/api/testGenerateCircles.js
utils/backendApi.js
utils/generateCirclesCenter.js

running npm run format

---

app/(main)/Analysis/page.tsx
components/landingpage/HeaderContent.tsx
components/landingpage/PulsingPicture.tsx

Analysis page content. still, one animation is missing.
just make sure that the missing content is added to dev ad nothing get deleted or so from dev

added analysis animation

---

app/(main)/Analysis/page.tsx
components/landingpage/HeaderContent.tsx

fixed formatting

---

app/(NoLogoPages)/StatusMgr/[step]/page.tsx
components/Status/GroupStatus.tsx

Fixing erros from Fadi's latest pull requests. (Still need to make sure everything works as it's supposed to)

Fix GroupStatus Props Handling

---

app/layout.tsx
components/DiningTime/DiningTimeForm.tsx
components/Status/GroupStatus.tsx
components/landingpage/HeaderContent.tsx
package-lock.json
package.json

Adding monitoring to two buttons on dev:
- Group Creation
- Restaurant Generation
This might need to be adjusted after the FE and BE is connected.

Monitoring implemented to two buttons

---

actions/auth.ts
actions/functions.ts
components/signup/SignupForm.tsx
components/signup2/Signup2Form.tsx
components/static/CountrySelectList.tsx
components/ui/command.tsx
components/ui/dialog.tsx
components/ui/popover.tsx
package-lock.json
package.json
pages/api/testGroup.ts
utils/types/supabase.ts

Adding some frontend, especially adding the user into the users table

Backend frontend fadi

---

app/layout.tsx

layout updated to only show intercom on landing and home page

layout file updated to show intercom on landing and home page

---

actions/avatarfunctions.ts
components/Avatar/AvatarForm.tsx

avatar functions and avatar component

avatar functions and changes to avatar component

---

actions/functions.ts
app/(NoLogoPages)/(Quiz)/Cuisine/page.tsx
app/(NoLogoPages)/StatusMbr/[step]/page.tsx
app/(NoLogoPages)/StatusMgr/[step]/page.tsx
components/GroupName/GroupNameForm.tsx
components/Home/Banner.tsx
components/QuizPages/BudgetSelectorForm.tsx
components/QuizPages/CompletedForm.tsx
components/QuizPages/CuisineForm.tsx
components/Status/GroupStatus.tsx
context/QuizContext.tsx
package-lock.json
package.json
utils/updateUserConstraints.ts

creators can go from home page to completing quiz without any problems, can go back to changing their quiz choices as well

130 complete flow through quiz without hardcoding

---

actions/functions.ts
app/(NoLogoPages)/StatusMgr/[step]/page.tsx
components/QuizPages/BudgetSelectorForm.tsx
components/QuizPages/CompletedForm.tsx
components/Status/GroupStatus.tsx
components/Status/MemberStatus.tsx

tested with two group members, the creator of the group 
uses default avatars for now

133 fetch non hard coded members of group

---

app/Result/page.tsx
components/Status/ConfirmGenerate.tsx
components/Status/GroupStatus.tsx
components/Status/new.tsx

when creator oresses generate he get taken to rsults page, the results page has access to group id via props now

overlay of the warning, user gets sent to results page with the group id

---

actions/functions.ts
app/(NoLogoPages)/StatusMbr/[step]/page.tsx
app/(NoLogoPages)/StatusMgr/[step]/page.tsx
components/Home/GroupJoinForm.tsx
components/QuizPages/CompletedForm.tsx

use group code to finish quiz and it remembers you are a group member and not a creator

135 group member flow using group code

---

app/(NoLogoPages)/StatusMgr/[step]/page.tsx
app/layout.tsx
components/GroupName/GroupNameForm.tsx
components/Home/GroupJoinForm.tsx
components/Status/GroupStatus.tsx
context/GroupContext.tsx

works for both member and manager

group code copying works

---

actions/avatarfunctions.ts
app/(main)/Settings/page.tsx
app/layout.tsx
components/AccountDetails/AccountForm.tsx
components/Avatar/AvatarForm.tsx
components/Settings/ProfileHeader.tsx
components/Status/GroupStatus.tsx
components/Status/MemberStatus.tsx
components/static/Avatar.tsx
context/UserContext.tsx

fetching done on start of website, stored in context
home page u do not to fetch it
also in status page u need to fetch it because it is other peoples id, no need to store theirs locally

146 correct avatars for users

---

actions/functions.ts
components/Home/GroupItemCard.tsx
components/QuizPages/CompletedForm.tsx
components/Status/GroupStatus.tsx

previous groups works

---

components/Analysis/PulsingPicture.tsx

Remove hardcode for finding restaurant

Update PulsingPicture.tsx to remove hardcode

---

components/Settings/SettingsForm.tsx

help and support in settings

---

components/AccountDetails/AccountForm.tsx
components/AccountDetails/FormField.tsx
components/static/CountrySelectList.tsx

budget selecter input correctly on the page

---

components/QuizPages/CuisineForm.tsx
components/QuizPages/VerticalCarousel.tsx

shrinking issue that is fixed needs to be added to dev

192 add quiz options
